version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis_server
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

volumes:
  redis_data:
    driver: local
